version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: ppt-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: >
      redis-server /usr/local/etc/redis/redis.conf
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --save 60 10000
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ppt-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ppt-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: "local:ppt-redis:6379"
      HTTP_USER: admin
      HTTP_PASSWORD: RedisAdmin123!
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ppt-network

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: ppt-redis-insight
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/db
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ppt-network

volumes:
  redis_data:
    driver: local
  redisinsight_data:
    driver: local

networks:
  ppt-network:
    driver: bridge
    external: false