version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ppt-postgres
    environment:
      POSTGRES_DB: ppt_generator
      POSTGRES_USER: ppt_admin
      POSTGRES_PASSWORD: SecurePass123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ppt_admin -d ppt_generator"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ppt-network

  # Redis Cache & Message Broker
  redis:
    image: redis:7.2-alpine
    container_name: ppt-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: >
      redis-server /usr/local/etc/redis/redis.conf
      --appendonly yes
      --appendfsync everysec
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ppt-network

  # pgAdmin for PostgreSQL Management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ppt-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pptgen.com
      PGADMIN_DEFAULT_PASSWORD: AdminPass123!
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ppt-network

  # Redis Commander for Redis Management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ppt-redis-commander
    environment:
      REDIS_HOSTS: "local:ppt-redis:6379"
      HTTP_USER: admin
      HTTP_PASSWORD: RedisAdmin123!
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ppt-network

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  ppt-network:
    name: ppt-network
    driver: bridge